POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvbmFobWFyIiwiaWQiOiI2NzNkMGE3NGVlZThiZjczMDI5NDY2MDEiLCJpYXQiOjE3MzIyMTYwNzJ9.vJ03inV_6oxRlXKyBhVH-F4yYTdaGeLxqKLyN1xPt1M

{
    "title": "All The Beauty In The World",
    "author": "Patrick Bringley",
    "url": "https://bookoftheday.org/all-the-beauty-in-the-world-the-metropolitan-museum-of-art-and-me-patrick-bringley/",
    "likes": 326
}
